default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: diet_maker_development

test:
  <<: *default
  database: diet_maker_test

production:
  <<: *default
  database: diet_maker_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>