default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: training_db_development

test:
  <<: *default
  database: training_db_test

production:
  <<: *default
  database: training_db_production
  username: postgres
  password: password