default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: training_db_development
  username: postgres
  password: password
  host: db

test:
  <<: *default
  database: training_db_test
  username: postgres
  password: password
  host: db

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>