default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost
  database: backend_development
  socket: /tmp/mysql.sock

test:
  <<: *default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost
  database: backend_test
  socket: /tmp/mysql.sock

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  username: backend
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>