app = "diet-maker"

[build]
  dockerfile = "./backend/Dockerfile"

[env]
  PORT = "3000"
  DATABASE_URL = "postgres://postgres:password@db/training_db_production"

[deploy]
release_command = "bundle exec rails db:migrate"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443