app = "diet-maker"

[build]
dockerfile = "./backend/Dockerfile"

[deploy]
release_command = "bundle exec rails db:migrate"
cmd = ["sh", "-c", "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"]

[env]
PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[mounts]]
  source = "my_app_data"
  destination = "/data"