app = "diet-maker"

[build]
dockerfile = "./backend/Dockerfile"
context = "./backend"

[deploy]
release_command = "bundle exec rails db:migrate"

[env]
PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443