app = "diet-maker"

[build]
dockerfile = "./backend/Dockerfile"

[deploy]
release_command = "bundle exec rails db:migrate"

[env]
PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  cmd = ["sh", "-c", "rm -f /myapp/tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443