source "https://rubygems.org"

ruby "3.3.6"

gem "rails", "~> 7.1.5"
gem "pg", ">= 1.2.3"
gem "puma", ">= 5.0"
gem "bcrypt", "~> 3.1.7"
gem "tzinfo-data", platforms: %i[ mswin jruby ]
gem "bootsnap", require: false
gem 'dotenv-rails'

group :development, :test do
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "web-console", ">= 4.1.0"
  gem 'dotenv-rails', groups: [:development, :test]
end

group :development do
  gem "listen", "~> 3.3"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

group :test do
  gem "capybara", ">= 3.26"
  gem "selenium-webdriver"
  gem "webdrivers"
end

group :production do
  gem "rails_12factor"
end