source "https://rubygems.org"

gem "rails", "~> 7.2.2", ">= 7.2.2.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]
gem "bootsnap", require: false
gem 'sprockets-rails', '>= 2.0.0'

group :development, :test do
  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "sqlite3", "~> 1.4"
end

group :production do
  gem 'pg', '~> 1.2.3'
end

# Add railties gem
gem 'railties', '~> 7.2.2'

# Add jsbundling-rails gem
gem 'jsbundling-rails'
